// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type RefreshToken struct {
	TokenID   int32         `json:"token_id"`
	Token     string        `json:"token"`
	UserID    sql.NullInt32 `json:"user_id"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}

type User struct {
	UsersID   int32     `json:"users_id"`
	PublicID  uuid.UUID `json:"public_id"`
	Username  string    `json:"username"`
	Password  string    `json:"password"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
