// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package store

import (
	"context"
	"database/sql"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (token, user_id)
VALUES ($1, $2)
RETURNING token_id, token, user_id, created_at, updated_at
`

type CreateRefreshTokenParams struct {
	Token  string        `json:"token"`
	UserID sql.NullInt32 `json:"user_id"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.queryRow(ctx, q.createRefreshTokenStmt, createRefreshToken, arg.Token, arg.UserID)
	var i RefreshToken
	err := row.Scan(
		&i.TokenID,
		&i.Token,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTokenByUserID = `-- name: DeleteTokenByUserID :exec
DELETE FROM refresh_tokens
WHERE user_id = $1
`

func (q *Queries) DeleteTokenByUserID(ctx context.Context, userID sql.NullInt32) error {
	_, err := q.exec(ctx, q.deleteTokenByUserIDStmt, deleteTokenByUserID, userID)
	return err
}

const getTokenByID = `-- name: GetTokenByID :one
SELECT token_id, token, user_id, created_at, updated_at
FROM refresh_tokens
WHERE token_id = $1
`

func (q *Queries) GetTokenByID(ctx context.Context, tokenID int32) (RefreshToken, error) {
	row := q.queryRow(ctx, q.getTokenByIDStmt, getTokenByID, tokenID)
	var i RefreshToken
	err := row.Scan(
		&i.TokenID,
		&i.Token,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTokenByTokenString = `-- name: GetTokenByTokenString :one
SELECT token_id, token, user_id, created_at, updated_at
FROM refresh_tokens
WHERE token = $1
`

func (q *Queries) GetTokenByTokenString(ctx context.Context, token string) (RefreshToken, error) {
	row := q.queryRow(ctx, q.getTokenByTokenStringStmt, getTokenByTokenString, token)
	var i RefreshToken
	err := row.Scan(
		&i.TokenID,
		&i.Token,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
